sampleApp:
  meta:
    minReplicas: 1
    maxReplicas: 10
  image:
    tag: latest
  service:
    type: ClusterIP
    port: 80
    targetport: 80
  replicas: 8
  resources:
    requests:
      memory: 100
      cpu: 100
    limits:
      memory: 200
      cpu: 200
    targetAverageUtilization: 50
