sampleApp:
  meta:
    minReplicas: 1
    maxReplicas: 10
  image:
    tag: latest
  service:
    type: ClusterIP
    port: 80
    targetport: 80
  replicas: 8
  resources:
    requests:
      memory: 64
      cpu: 64
    limits:
      memory: 128
      cpu: 128
    targetAverageUtilization: 50
