apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: {{ .Values.sampleApp.meta.replicas }}
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - image: maniaksreg.azurecr.io/nginx:{{ .Values.sampleApp.image.tag }}
        name: sample-app
        resources:
          requests:
            memory: {{ .Values.sampleApp.resources.requests.memory }}Mi
            cpu: {{ .Values.sampleApp.resources.requests.cpu }}
          limits:
            memory: {{ .Values.sampleApp.resources.limits.memory }}Mi
            cpu: {{ .Values.sampleApp.resources.limits.cpu }}
