apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app
spec:
  minReplicas: {{ .Values.sampleApp.meta.minReplicas }}
  maxReplicas: {{ .Values.sampleApp.meta.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.sampleApp.resources.targetAverageUtilization }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.sampleApp.resources.targetAverageUtilization }}
