apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  ports:
  - port: {{ .Values.sampleApp.service.port }}
    protocol: TCP
    targetPort: {{ .Values.sampleApp.service.targetport }}
  selector:
    app: sample-app
  type: ClusterIP
