trigger:
- task: Packer@1
  inputs:
    connectedServiceType: 'azure'
    azureSubscription: 'RAPYDER-POC-SUBSCRIPTION(cf22be19-a8a1-4e16-94a6-e77eb06f8d3e)'
    templatePath: 'packer'
    command: 'build'
    variables: '-var "managed_image_name=myPackerImage-2" -var "resource_group=mani-poc" -var "client_id=82b29915-3f0d-46d7-9f21-c62c0451fa79" -var "client_secret=LaD8Q~0X8-XoNg76bpTnpTuaGzfoza22zLttlalL" -var "location=centralindia" -var "subscription_id=cf22be19-a8a1-4e16-94a6-e77eb06f8d3e" -var "tenant_id=ee873d89-a26e-47cf-8019-b65d6ee4d46c" -var "vm_size=Standard_B1ls"'
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'terraform'
        artifactName: 'terraform'
        publishLocation: 'Container'
    - task: Packer@1
      inputs:
        connectedServiceType: 'azure'
        azureSubscription: 'RAPYDER-POC-SUBSCRIPTION(cf22be19-a8a1-4e16-94a6-e77eb06f8d3e)'
        templatePath: 'packer'
        command: 'build'
        variables: '-var "managed_image_name=myPackerImage-2" -var "resource_group=mani-poc" -var "client_id=82b29915-3f0d-46d7-9f21-c62c0451fa79" -var "client_secret=LaD8Q~0X8-XoNg76bpTnpTuaGzfoza22zLttlalL" -var "location=centralindia" -var "subscription_id=cf22be19-a8a1-4e16-94a6-e77eb06f8d3e" -var "tenant_id=ee873d89-a26e-47cf-8019-b65d6ee4d46c" -var "vm_size=Standard_B1ls"'

#- stage: Deploy
#  jobs:
#  - deployment: KubernetesDeploy
#    displayName: Deploy App
#    pool:
#      vmImage: 'ubuntu-20.04'
#    environment: 'm8nkops'
#    strategy:
#      runOnce:
#        deploy:
#          steps:
#          - download: current
#            artifact: chart
#          - script: |
#              az login --service-principal -u $(azureArmClientId) -p $(azureArmClientSecret) --tenant $(azureArmTenantId)
#              #echo "Switch Dorectory"
#              cd /home/vsts/work/1/
#              az aks get-credentials --resource-group mani-poc --name mani-aks --admin
#              helm upgrade sample-app chart -i --set sampleApp.image.tag=$(tag) -n azure
#            displayName: 'Deploy in AKS'
